services:
  app:
    container_name: control361-app
    image: control361-app
    build: .
    working_dir: /app
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
